import Head from "next/head";
import TopBar from "../components/TopBar/topBar";
import SearchBar from "../components/SearchBar/searchBar";
import React from "react";
import { Container, Main, Footer } from "../styles/home.styles";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

/**
 * Home page of the application
 * @returns
 */

export default function Home() {
  const { t } = useTranslation("common");
  return (
    <Container>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plane.png" />
      </Head>
      <Main>
        <TopBar> </TopBar>
        <SearchBar></SearchBar>
      </Main>

      <Footer>
        <a href="https://google.com" target="_blank" rel="noopener noreferrer">
          Powered by FlightX
        </a>
      </Footer>
    </Container>
  );
}

interface Props {
  locale: string;
}

export async function getStaticProps({ locale }: { locale: any }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "footer"])),
    },
  };
}
